Gradient_Descent_Raw:
	/home/yifan/cuda-5.5/bin/nvcc -I/usr/local/MATLAB/R2013a/extern/include -L/usr/local/MATLAB/R2013a/bin/glnxa64  -g -o Gradient_Descent_Cublas  Gradient_Descent_Cublas.cu -lmat -lmx -lm -lcublas
