Gradient_Descent_Cuda:
	/home/yifan/cuda-5.5/bin/nvcc -ccbin g++  -I../../common/inc -I/usr/local/MATLAB/R2013a/extern/include -L/usr/local/MATLAB/R2013a/bin/glnxa64 -m64  -gencode arch=compute_20,code=compute_20    -g -G   -o Gradient_Descent_Cuda Gradient_Descent_Cuda.cu -lmat -lmx -lm 
